export const appName = 'New Concept English Learning App'
export const appDescription = 'New Concept English Learning App'
export const storageKeySoundEnable = 'nce-sound-enable'
export const storageKeyLessonMode = 'nce-lesson-mode'
export const storageKeyLastLesson = 'nce-last-lesson'
export const storageKeyChoice = 'nce-choice'
export const HOST = 'http://139.159.153.45:3004'
